#!/usr/bin/env bash
# Continuously prints "To infinity and beyond" and responds to SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
